(
    "Mozilla.Firefox",
    #"ojdkbuild.ojdkbuild",
    "eloston.ungoogled-chromium",
    "CodecGuide.K-LiteCodecPackMega",
    "Transmission.Transmission",
    "FileConverter.FileConverter",
    "7zip.7zip",
    #"ONLYOFFICE.DesktopEditors",
    "OBSProject.OBSStudio",
    "Oracle.JavaRuntimeEnvironment",
    "KeePassXCTeam.KeePassXC",
    "Mozilla.Thunderbird",
    "AnyDeskSoftwareGmbH.AnyDes",
    "Telegram.TelegramDesktop",
    "Rufus.Rufus",
) | foreach {winget install -e --id $_}